# Generated by Django 4.2.14 on 2025-04-11 04:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="set", options={"ordering": ["workout_exercise", "order"]},
        ),
        migrations.AlterModelOptions(name="workout", options={"ordering": ["date"]},),
        migrations.AlterModelOptions(
            name="workoutexercise", options={"ordering": ["workout", "order"]},
        ),
        migrations.RemoveField(model_name="workout", name="length",),
        migrations.AddField(
            model_name="set",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workout",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workout.workout",
            ),
            preserve_default=False,
        ),
    ]
