# Generated by Django 4.2.14 on 2025-04-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("muscle_name", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_name", models.CharField(max_length=100, unique=True)),
                (
                    "muscles_worked",
                    models.ManyToManyField(
                        related_name="muscles_worked", to="movement.muscle"
                    ),
                ),
            ],
        ),
    ]
