# Generated by Django 4.2.14 on 2025-04-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="movement", options={"ordering": ["name"]},),
        migrations.AlterModelOptions(name="muscle", options={"ordering": ["name"]},),
        migrations.RenameField(
            model_name="movement", old_name="movement_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="muscle", old_name="muscle_name", new_name="name",
        ),
        migrations.AddField(
            model_name="movement",
            name="movement_image_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="type",
            field=models.CharField(
                choices=[("strength", "Strength"), ("cardio", "Cardiovascular")],
                default="strength",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="muscle",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("arms", "Arms"),
                    ("back", "Back"),
                    ("chest", "Chest"),
                    ("core", "Core"),
                    ("legs", "Legs"),
                    ("shoulders", "Shoulders"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="muscles_worked",
            field=models.ManyToManyField(
                related_name="movements", to="movement.muscle"
            ),
        ),
    ]
