# Generated by Django 5.2 on 2025-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0002_alter_movement_options_alter_muscle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
