# Generated by Django 4.2.14 on 2025-04-11 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_friendship_customuser_friends"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship", options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="friendship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
