# Generated by Django 4.2.14 on 2025-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
