name: PeakPerformance CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.filter.outputs.frontend }}
      backend-changed: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          filters: |
            frontend:
              - 'peakperformance_backend/**'
            backend:
              - 'backend/**'

  build-and-test-frontend:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Run frontend build script
        run: npm build
      
      - name: Run frontend test script
        run: npm frontend

  build-and-test-backend:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Docker Compose
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          DEBUG: ${{secrets.DEBUG}}
          ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
          POSTGRES_DB: ${{secrets.POSTGRESS_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          EMAIL_BACKEND: ${{secrets.EMAIL_BACKEND}}
          EMAIL_HOST: ${{secrets.EMAIL_HOST}}
          EMAIL_PORT: ${{secrets.EMAIL_PORT}}
          EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
          EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
          DEFAULT_FROM_EMAIL: ${{secrets.DEFAULT_FROM_EMAIL}}
          EMAIL_USE_TLS: ${{secrets.EMAIL_USE_TLS}}
          EMAIL_USE_SSL: ${{secrets.EMAIL_USE_SSL}}
          
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Run backend build script
        run: python backend/scripts/build_image.py --env ci
      
      - name: Run backend test script
        run: python backend/scripts/run_tests.py --env ci

  # This job runs regardless of which part changed, useful for deployment or other steps
  final-steps:
    needs: [detect-changes, build-and-test-frontend, build-and-test-backend]
    if: |
      always() && 
      (needs.detect-changes.outputs.frontend-changed == 'true' || needs.detect-changes.outputs.backend-changed == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Final verification step
        run: echo "All tests run successfully!"